[package]
name = "dsl"
edition = "2024"
version.workspace = true

[dependencies]
clap.workspace = true
init = { path = "../crates/init" }
parse = { path = "../crates/parse" }
render = { path = "../crates/render" }
validate = { path = "../crates/validate" }
watch = { path = "../crates/watch" }
lint = { path = "../crates/lint" }
